### ISSUE TITLE
[feature] Filter Rating Star

### ISSUE THREAD

**Issue by gydoma** [gydoma/arcade#24]
As in the sketch wireframe, show the stars and the numbers in the search & filter menu. As the slider moves the numbers go from 1.0 (since you can't rate 0 stars) to 5.0 and the stars changes as below:

- ../resources/rating/Empty.svg 1.0=<
- ../resources/rating/Half.svg 3.0=<
- ../resources/rating/Full.svg 5.0=<

**Comment by KatRoland** [comment]
Completed
